# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dht.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tdht.proto\"(\n\x07\x41\x44\x44RESS\x12\x0f\n\x07ip_addr\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"-\n\x04JOIN\x12\n\n\x02id\x18\x01 \x01(\r\x12\x19\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x08.ADDRESS\"^\n\x07JOIN_OK\x12\x13\n\x04node\x18\x01 \x01(\x0b\x32\x05.JOIN\x12\x1e\n\x0csucc_address\x18\x03 \x01(\x0b\x32\x08.ADDRESS\x12\x1e\n\x0cpred_address\x18\x04 \x01(\x0b\x32\x08.ADDRESS\"&\n\x08TRANSFER\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\t\"$\n\x08NEW_NODE\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"3\n\x05LEAVE\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1e\n\x0cpred_address\x18\x02 \x01(\x0b\x32\x08.ADDRESS\";\n\tNODE_GONE\x12\n\n\x02id\x18\x01 \x01(\r\x12\"\n\x10new_succ_address\x18\x02 \x01(\x0b\x32\x08.ADDRESS\"#\n\x05STORE\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\x0c\"<\n\x08RETRIEVE\x12\x0b\n\x03key\x18\x01 \x01(\r\x12#\n\x11requester_address\x18\x02 \x01(\x0b\x32\x08.ADDRESS\"+\n\x02OK\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\t\n\x01n\x18\x02 \x01(\x05\x12\r\n\x05value\x18\x03 \x01(\x0c\"\x0b\n\tNOT_FOUND2U\n\rDhtOperations\x12\x1f\n\x0cjoin_network\x12\x05.JOIN\x1a\x08.JOIN_OK\x12#\n\rleave_network\x12\x06.LEAVE\x1a\n.NODE_GONEb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dht_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDRESS']._serialized_start=13
  _globals['_ADDRESS']._serialized_end=53
  _globals['_JOIN']._serialized_start=55
  _globals['_JOIN']._serialized_end=100
  _globals['_JOIN_OK']._serialized_start=102
  _globals['_JOIN_OK']._serialized_end=196
  _globals['_TRANSFER']._serialized_start=198
  _globals['_TRANSFER']._serialized_end=236
  _globals['_NEW_NODE']._serialized_start=238
  _globals['_NEW_NODE']._serialized_end=274
  _globals['_LEAVE']._serialized_start=276
  _globals['_LEAVE']._serialized_end=327
  _globals['_NODE_GONE']._serialized_start=329
  _globals['_NODE_GONE']._serialized_end=388
  _globals['_STORE']._serialized_start=390
  _globals['_STORE']._serialized_end=425
  _globals['_RETRIEVE']._serialized_start=427
  _globals['_RETRIEVE']._serialized_end=487
  _globals['_OK']._serialized_start=489
  _globals['_OK']._serialized_end=532
  _globals['_NOT_FOUND']._serialized_start=534
  _globals['_NOT_FOUND']._serialized_end=545
  _globals['_DHTOPERATIONS']._serialized_start=547
  _globals['_DHTOPERATIONS']._serialized_end=632
# @@protoc_insertion_point(module_scope)
